### ISSUE TITLE
[Feature Request]: Store Message Reactions in the Database

### ISSUE THREAD

**Issue by muskan171105** [kartikayasijaa/talk-trove#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently, message reactions are handled in real-time using Socket.io but are not saved in the database. To ensure reactions persist across sessions and are available for historical messages, we need to store reactions in the database.

**Tasks:**
1. Modify the message schema to include a `reactions` field (e.g., with user ID and reaction type).
2. Update the `reactMessage` event to save reactions in the database.
3. Fetch and display reactions when retrieving messages.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sibam-Paul** [comment]
If u have any problem please open a question/answer tab in the discussion section of this repo plz it would be helpful 
and always look at it for announcement plz of any changes we will make regarding issues

**Comment by Sibam-Paul** [comment]
Please see discussion tab and join discord plz @muskan171105
